### ISSUE TITLE
Can't find file

### ISSUE THREAD

**Issue by thomhurst** [timescale/timescaledb-tune#37]
Windows 10

Ran this in powershell and got:
```
PS C:\Users\tom> timescaledb-tune
[31;1mexit: [0mcould not find postgresql.conf at any of these locations:

```

I ran `psql -U postgres -c 'SHOW config_file'` and it output this >
`C:/PostgreSQL/data/pg11/postgresql.conf`

**Comment by RobAtticus** [comment]
You should be able to use that path and call timescaledb-tune:
```
timescaledb-tune --pg-config="C:\Users\tom> timescaledb-tune"
````

**Comment by RobAtticus** [comment]
Hi @thomhurst any luck with that?

**Comment by thomhurst** [comment]
Yup it worked fine! 
I ran `psql -U postgres -c 'SHOW config_file'` to get `C:/PostgreSQL/data/pg11/postgresql.conf`
Then I ran `timescaledb-tune --pg-config="C:/PostgreSQL/data/pg11/postgresql.conf"` and it worked as expected.

I just raised this as your readme said 

> or auto-detection fails (file an issue please!)

Thanks!

**Comment by RobAtticus** [comment]
Ah yes, true. Still working on improving Windows auto-detection :) Thanks for the issue!

**Comment by AEzzatA** [comment]
By the way, that still happens when running a fresh Docker image 

Here is how it went
```
➜  timescaledb-docker: docker run -d --name timescale -p 5555:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg11

docker exec -it timescale bash

bash-4.4# su postgres

/ $ timescaledb-tune 

/etc/postgresql/11/main/postgresql.conf
/var/lib/pgsql/11/data/postgresql.conf
/var/lib/postgres/data/postgresql.conf


/ $ psql -U postgres -c 'SHOW config_file'
               config_file                
------------------------------------------
 /var/lib/postgresql/data/postgresql.conf
(1 row)
```

**Comment by RobAtticus** [comment]
@AEzzatA, thanks for the report. This was fixed in https://github.com/timescale/timescaledb-tune/pull/45 which will go out with the next TimescaleDB release (~next week).

Also, the Docker image usually runs timescaledb-tune by default as part of its startup process.

**Comment by OmkarNeogi** [comment]
Ran across a similar issue on Mac because `brew install postgres@11` creates a directory called `postgresql@11` instead of `postgres` as is expected by the timescaledb-tune. I renamed the directory myself (to `postgres`) and it worked. I am not sure if renaming the directory will cause issues for brew - open to suggestions on this.
On trying the pg-config option, I got a permission denied. On trying with sudo as well, I got permission denied.
```
$ timescaledb-tune --pg-config="/usr/local/var/postgresql@11/postgresql.conf"
exit: could not execute `/usr/local/var/postgresql@11/postgresql.conf --version`: fork/exec /usr/local/var/postgresql@11/postgresql.conf: permission denied
```
I did `brew install postgresql@11` and not `brew install postgresql` as is usually done to get the latest version. Even if I had done `brew install postgresql`, the directory created by brew would be `postgresql` and not `postgres`. The https://docs.timescale.com/latest/getting-started/installation/macos/installation-homebrew does not mention having to pass in the pg-conf parameter while running `timescaledb-tune`. Is there a better way to do this?

**Comment by milespomeroy** [comment]
@OmkarNeogi  for Mac I had to use this command to get it to work
```bash
timescaledb-tune --quiet --yes --pg-config /usr/local/opt/postgresql@11/bin/pg_config --conf-path /usr/local/var/postgresql@11/postgresql.conf
```

**Comment by fergus3000** [comment]
Thank you @milespomeroy I had a similar problem on windows, with an installation where the pg binaries were on a different disk to pg data. I had to use the following
`.\timescaledb-tune.exe --pg-config="C:/Program Files/PostgreSQL/11/bin/pg_config.exe" --conf-path="F:/Program Files/PostgreSQL/11/data/postgresql.conf"`

**Comment by svenklemm** [comment]
Seams to be solved
