### ISSUE TITLE
wal-disk-size switch doesn't behave as expected

### ISSUE THREAD

**Issue by jflambert** [timescale/timescaledb-tune#67]
First of all the wal-disk-size switch isn't documented on the readme and it probably should be.

Second, I looked at wal.go to try and understand the behavior, [specifically this commit](https://github.com/timescale/timescaledb-tune/commit/99705cea7cf6b46d988baaab7f80ced5860e17b0). It says that `max_wal_size` will be 80% of the space given, but my tests  show it's more like 60% actually.

`timescaledb-tune -dry-run -conf-path /var/lib/postgres/data/pgdata/postgresql.conf -wal-disk-size 100GB -yes`

> WAL settings recommendations
> Current:
> min_wal_size = 512MB
> max_wal_size = 1GB
> Recommended:
> min_wal_size = 30GB
> max_wal_size = 60GB
> success: WAL settings will be updated

Finally, why not just use the same settings as [PGTune](https://pgtune.leopard.in.ua/#/), which [depend on profile types](https://github.com/le0pard/pgtune/blob/ccf5a4c830819d2131345e8bf083c3c5ca453a89/webpack/selectors/configuration.js#L169)? It's my understanding that timescaledb-tune more or less uses the "data warehouse" settings, and I'd be happy with 4GB/16GB. 

Until then, I will manually force the settings instead of relying on timescaledb-tune.

**Comment by RobAtticus** [comment]
Thanks for the issue. Here are a couple of thoughts:

1) Good catch on missing it in the README, we'll fix that.

2) It is 60% because of a subsequent commit: https://github.com/timescale/timescaledb-tune/commit/fc5c6aba892befe506a097a11538fd664d9303dd
I guess the comment in that file is probably outdated

3) Static settings like 4/16GB are not great for disk sizes that are on the smaller end, especially if you are sharing disk and WAL volumes. If you are using e.g. a 25GB shared disk (which can potentially hold 100-250GB data pre-compression) and 16GB could be used for WAL you might find yourself out of disk space much sooner than you anticipate. Allowing larger WAL volumes also helps for replication where a large of data is backlogged (e.g. one of the replicas dies and data needs to be held until it returns).

I will also cc @feikesteenbergen who originally suggested this change I believe.

**Comment by jflambert** [comment]
2) you're right, I'm wrong. It's 60% and the comment is fixed in the latest file. Not sure why I focused on that commit.

3) for a 1TB disk (or more, way more), does the 60% still make sense for max_wal_size? I kind of freaked out seeing 300GB/600GB as suggested values.

Another issue here is having to specify the disk size, it feels like the tool should do that automatically from passing the conf-path as a parameter...

**Comment by feikesteenbergen** [comment]
Just trying to understand the issue here, the main purpose (which we should add to the README) of this behavior is to support a dedicated WAL Volume.

@jflambert Do you want to tune your instance for a dedicated WAL Volume?

The trigger to teach timescaledb-tune to configure larger WAL volumes was that with some continuous throughput scenarios (100K+ rows per second for multiple days) we needed WAL Volumes of 500GB+, where we were generating multiple GB's of WAL per minute.

Having WAL configured to 4/8/16GB would not be good for performance in this situation, it would cause checkpoints to occur too frequently.

**Comment by RobAtticus** [comment]
> 2. for a 1TB disk (or more, way more), does the 60% still make sense for max_wal_size? I kind of freaked out seeing 300GB/600GB as suggested values.

If that disk is used exclusively for the WAL, then yes. If it is a shared volume, then you would probably just specify a portion of that disk to be "WAL" space, so maybe 5-10%.

>Another issue here is having to specify the disk size, it feels like the tool should do that automatically from the configuration file.

I can see this as an issue. It's hard to tell the right approach here, since if we do calculate the disk space available at the volume where PG is storing its WAL, we can't be sure whether to assume all of its available for WAL (dedicated disk) or not (shared disk, i.e. data volume is the same as WAL volume).

**Comment by RobAtticus** [comment]
For what it's worth, you may find performance to be acceptable by not specifying the flag and sticking with the default WAL settings given by PG. It's only as you dig in deeper to your use case that it may be worth tuning.

**Comment by jflambert** [comment]
> For what it's worth, you may find performance to be really good even without specifying the flag and sticking with the default WAL settings given by PG. It's only as you dig in deeper to your use case that it may be worth tuning.

I've been getting these warnings:

> 2020-04-06 05:29:10.592 UTC [13] LOG: checkpoints are occurring too frequently (27 seconds apart)

2020-04-06 05:29:10.592 UTC [13] HINT: Consider increasing the configuration parameter "max_wal_size".

**Comment by RobAtticus** [comment]
Cool, then I would try specifying only a portion of your disk as WAL for that flag. So if your total disk is 100GB, say 10GB?

**Comment by RobAtticus** [comment]
(Assuming your data and WAL share the same 100GB volume.)

**Comment by jflambert** [comment]
> (Assuming your data and WAL share the same 100GB volume.)

It's more likely to be a 1TB+ volume and yes, data and WAL on same disk. What would you say then?

**Comment by RobAtticus** [comment]
If you like the 4/8GB that pgtune gives, then you can do something like 15GB or 20GB. My first guess would be no more than 50GB for that flag.

re: separate volumes - if you can do it, it is usually preferred. Especially in cloud environments where you have IOPS limits you'll get better performance by having them use separate IOPS buckets. But if your performance is good and it would add unnecessary operational overhead and cost, you can continue to use the same volume.

**Comment by svenklemm** [comment]
I think this is fixed now, feel free to reopen if it isnt.
